sudo: required
language: go
go:
 - 1.6
 - tip

services:
  - cassandra

before_install:
  - CASSANDRA_IP_ADDRESS=127.0.0.1
  - export CASSANDRA_IP_ADDRESS
  - sudo apt-get update
  - sudo apt-get install -y net-tools

script:
 - go test -v ./...
 - netstat -nl
 - go test -v data/service/AddressDataServiceCreateIntegration_test.go
