language: go
go:
 - 1.6
 - tip

services:
  - cassandra

before_install:
  - CASSANDRA_IP_ADDRESS=127.0.0.1
  - export CASSANDRA_IP_ADDRESS

script:
 - go test -v ./...
 - go test -v data/service/AddressDataServiceCreateIntegration_test.go
